### ISSUE TITLE
BBZ BL

### ISSUE THREAD

**Issue by rampd2** [ok2094/gibmtimetable#1]
GIBM has renamed/merged to BBZ BL (Berufsbildungszentrum Baselland), [as written here](https://www.bbzbl.ch/allgemein/herzlich-willkommen-am-bbz-bl/), thus the following adresses under sandbox.gibm.ch are no longer updated.

- https://sandbox.gibm.ch/berufe.php
- https://sandbox.gibm.ch/klassen.php
- https://sandbox.gibm.ch/tafel.php

https://github.com/okkdev/gibmschedule/blob/66d13fd5a73c4a421ec122459cb094861137fb6a/js/main.js#L3-L5

**Comment by okkdev** [comment]
That's unfortunate. Do you know if there is a new API?

**Comment by rampd2** [comment]
Yes it is. Sadly I don't know any new API Endpoints (yet).
_If I would find something I will update this issue and if possible update the code and make a pull request._

**Comment by rampd2** [comment]
I was mistaken, the adresses under `sandbox.gibm.ch` do get updates but were just incorrect a long time, so I thought they were dead.

_Also the data is a little "mixed" (diffrent ids), because of all these school classes from Liestal._

I know this because we have finished the modul 133 now (same timetable/schedule task).
<details>
<summary>api describing part of task sheet</summary>

![image](https://user-images.githubusercontent.com/12480131/150010590-968cae30-a85a-4b02-acd8-816c0c3063f7.png)

</details>

_I will close this issue, since for me it seems to be solved._
